version: "3.8"
services:
  database:
    image: mysql:8.0
    container_name: "mysqldb-8.0"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_USER=turreta
      - MYSQL_PASSWORD=turreta+pwd!
      - MYSQL_DATABASE=product-stock-management
      - MYSQL_ROOT_PASSWORD=for-testing
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - database:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database:
    driver: local
